# Generated by Django 4.1.7 on 2023-03-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_client_customuser_is_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='None', max_length=220, verbose_name='username'),
        ),
    ]
